import {
  Heading,
  Text,
  Stack,
  Box,
  Grid,
  GridItem,
  Spinner,
  Center,
  Flex,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import { FC, useEffect, useState } from "react";

export default function Home() {
  const [pokemons, setPokemons] = useState([]);
  const [waiting, setWating] = useState<boolean>(false);
  const getPokeData = async () => {
    setWating(true);
    const BASE_URL = "https://pokeapi.co/api/v2/";
    const f1 = await fetch(`${BASE_URL}pokemon?limit=100&offset=200`);
    const data = await f1.json();
    setPokemons(data.results);
    setWating(false);
    console.log(data);
  };
  useEffect(() => {
    getPokeData();
  }, []);
  type Props = {
    title: string;
    desc: string;
  };
  const StackItem: FC<Props> = ({ title, desc }) => {
    return (
      <Box
        cursor="pointer"
        p={5}
        shadow={"lg"}
        border={"1px"}
        borderColor="gray.200"
        rounded="lg"
      >
        <Heading fontSize={"lg"}>{title}</Heading>
        <Text mt={2}>{desc}</Text>
      </Box>
    );
  };
  return (
    <div>
      <Head>
        <title>PokeYS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        position="sticky"
        rounded="lg"
        sx={{
          /*
           * Seems Chakra UI doesn't have support for this property
           * Moving on ----
           */
          backgroundColor: "rgba(255,255,255,0.8)",
          backdropFilter: "blur(20px)",
        }}
        backdropBlur={20}
        inset="0"
        m={5}
        shadow="2xl"
        p={5}
      >
        <Heading
          bgGradient="linear(to-l, #7928CA,#FF0080)"
          bgClip="text"
          fontSize="6xl"
          fontWeight="extrabold"
          textAlign="center"
        >
          Welcome to the Poke App
        </Heading>

        <Flex direction="row" mt={10}>
          <Box width="50%" bg="gray.100" p="5" mr="5" rounded="lg">
            <Heading fontSize="2xl" color="indigo">
              Your Pocket
            </Heading>
            <Text>
              Add up to <span style={{ fontWeight: "bolder" }}>6</span> pokemons
              to your list
            </Text>
          </Box>
          <Grid
            templateColumns="repeat(3,1fr)"
            width="50%"
            p="5"
            bg="cyan.100"
            rounded="lg"
            placeItems="center"
          >
            <Text>Example</Text>
            <Text>Example</Text>
            <Text>Example</Text>
            <Text>Example</Text>
            <Text>Example</Text>
            <Text>Example</Text>
          </Grid>
        </Flex>
      </Box>

      {waiting && (
        <Center mt={20}>
          <Spinner size="xl" />
        </Center>
      )}
      <Grid gap={5} mt={5} templateColumns="repeat(4,1fr)" mx="5">
        {setWating &&
          pokemons.map((el, i) => (
            <div key={i}>
              <StackItem title={el.name} desc={el.url} />
            </div>
          ))}
      </Grid>
      <Center>
        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </Center>
    </div>
  );
}
