import {
  Heading,
  Text,
  Box,
  Grid,
  Spinner,
  Center,
  Flex,
  Button,
  useToast,
} from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { AlertComponent } from "../components/AlertComponent";
import { PokeCard } from "../components/PokeCard";
import { PokeTeamItem } from "../components/PokeTeamItem";
import { SearchForPoke } from "../components/SearchForPoke";
import { UserDefinedPoke } from "../components/UserDefinedPoke";
import { YourPocket } from "../components/YourPocket";
import { getSpecificPoke } from "../utils/getPokemon";

export default function Home() {
  // TODO CLEANUP A BIT HUH
  const BASE_URL = "https://pokeapi.co/api/v2";
  const [userPokes, setUserPokes] = useState([]);
  const [pokemonData, setPokemonData] = useState(null);
  const [waiting, setWating] = useState<boolean>(false);
  const [userPokeData, setUserPokeData] = useState(null);
  const [modalOpen, setModalOpen] = useState(false);
  const toast = useToast();

  const addToUserPocket = (pokemon) => {
    let newPoke = pokemon;
    let err2 = 0;
    userPokes.length === 0
      ? console.log("nothing to add")
      : userPokes.forEach((e) => {
          e.id === newPoke.id ? err2++ : console.log("alright");
        });

    err2 === 0 && setUserPokes((prev) => [...prev, newPoke]);
    err2 === 0 &&
      toast({
        title: "Pokemon added to your team!",
        status: "success",
        duration: 2000,
        isClosable: true,
      });
    err2 > 0 &&
      toast({
        title: "You already have this Pokemon",
        status: "error",
        duration: 1500,
        isClosable: true,
      });
  };

  /*
   * Get random poke
   */
  const generateRandomPoke = (s, f) => {
    setWating(true);
    const number = Math.floor(Math.random() * (f - s)) + s;
    fetch(`${BASE_URL}/pokemon/${number}`)
      .then((res) => res.json())
      .then((res) => {
        setWating(false);
        setPokemonData(res);
        console.log(res);
      });
    setWating(false);
  };
  // -------------------------------------------------

  const fetchThePoke = async (query) => {
    try {
      const userPokeData = await getSpecificPoke(query);
      setUserPokeData(userPokeData);
      console.log(userPokeData);
    } catch (err) {
      console.log(err);
      alert("This pokemon does not exist");
    }
  };

  // -------------------------------------------------
  useEffect(() => {
    generateRandomPoke(1, 898);
  }, []);

  return (
    <div>
      <Head>
        <title>PokeYS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid placeItems="center" gap={10} mx={20}>
        <Box rounded="lg" bg="white" shadow="2xl" p={5}>
          <Heading
            bgGradient="linear(to-l, #7928CA,#FF0080)"
            bgClip="text"
            fontSize="6xl"
            fontWeight="extrabold"
            textAlign="center"
          >
            Welcome to the Poke App
          </Heading>

          {/* User Team Component */}
          <YourPocket fnSetPokes={setUserPokes} dataUserPokes={userPokes} />
        </Box>
        <Button
          colorScheme="telegram"
          onClick={() => {
            generateRandomPoke(1, 898);
          }}
        >
          Generate New poke without refreshing the page!
        </Button>

        <SearchForPoke getPoKemonName={fetchThePoke} />
        {/* Waiting spinner */}
        {waiting && (
          <Center mt={20}>
            <Spinner size="xl" />
          </Center>
        )}
        {/* User Poke Card showing */}
        {userPokeData && (
          <UserDefinedPoke
            poke={userPokeData}
            inTeamPokeData={userPokes}
            fnSetInTeam={addToUserPocket}
          />
        )}
        {/* Showing the Card */}
        {!waiting && pokemonData && (
          <PokeCard
            addToTeam={addToUserPocket}
            setFn={setUserPokes}
            userPokes={userPokes}
            pokemonData={pokemonData}
          />
        )}
      </Grid>
    </div>
  );
}
